<?php

namespace App\Http\Requests;
use Illuminate\Validation\Rule;
use Illuminate\Foundation\Http\FormRequest;
use App\Rules\MatchPasswordConfirmation;
class StorePostRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'name' => 'required|min:6|max:30',
            'email' => ['required', 'email'],
            'country' => 'nullable|string|max:255',
            'password' => 'required|confirmed|min:8|max:30',
            'password_confirmation' => ['required'],
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function validatedWithDefaults()
    {
        $validatedData = $this->validated();
        // Định nghĩa các giá trị mặc định cho các trường dữ liệu mới
        $defaultValues = [
            'avatar' => '', // Đường dẫn mặc định cho avatar
            'role_id' => 1, // Giá trị mặc định cho trường role
            'status' => 'active', // Giá trị mặc định cho trường status
            'is_active' => true // Giá trị mặc định cho trường is_active
        ];

        // Gộp các giá trị mặc định vào dữ liệu đã được xác thực
        return array_merge($validatedData, $defaultValues);
    }
}
